owner: FootprintLab
repo: api-health

sites:
  - name: Activity Units
    url: $ACTIVITY_UNITS_URL
    headers:
      - "Authorization: Bearer $BEARER_TOKEN"
      - "x-api-key: $API_KEY"
      - "Content-Type: application/json"
    icon: https://data.footprintlab.io/favicon.ico

status-website:
  baseUrl: /api-health
  logoUrl: https://raw.githubusercontent.com/FootprintLab/api-health/refs/heads/master/assets/footprintlab_logo.png  
  name: FootprintLab API Health
  introTitle: "FootprintLab API Health Status"
  introMessage: "Welcome to the FootprintLab API Health status page. Here you can find the current status of our APIs and services."
  navbar:
    - title: Status
      href: /
  theme: light