# 🔼 Upptime @v1.40.1
# GitHub-powered open-source uptime monitor and status page by Anand Chowdhary

# * Source: https://github.com/upptime/upptime
# * Docs and more: https://upptime.js.org
# * More by Anand Chowdhary: https://anandchowdhary.com


name: Setup CI
on:
  push:
    paths:
      - ".upptimerc.yml"
  workflow_dispatch:
jobs:
  release:
    env:
      COGNITO_URL: ${{ secrets.COGNITO_URL }}
      COGNITO_CLIENT_ID: ${{ secrets.COGNITO_CLIENT_ID }}
      COGNITO_CLIENT_SECRET: ${{ secrets.COGNITO_CLIENT_SECRET }}
      API_KEY: ${{ secrets.API_KEY }}
    name: Setup Upptime
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_PAT || github.token }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Get Bearer Token
        id: get_token
        run: |
          TOKEN=$(curl -s -X POST "${COGNITO_URL}" \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -d "grant_type=client_credentials&client_id=${COGNITO_CLIENT_ID}&client_secret=${COGNITO_CLIENT_SECRET}" \
            | python3 -c "import sys, json; print(json.load(sys.stdin)['access_token'])" | tr -d '\r\n')
          echo "token=$TOKEN" >> $GITHUB_OUTPUT
      - name: Update response time
        uses: upptime/uptime-monitor@v1.40.1
        with:
          command: "response-time"
        env:
          GH_PAT: ${{ secrets.GH_PAT || github.token }}
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
          BEARER_TOKEN: ${{ steps.get_token.outputs.token }}
      - name: Update summary in README
        uses: upptime/uptime-monitor@v1.40.1
        with:
          command: "readme"
        env:
          GH_PAT: ${{ secrets.GH_PAT || github.token }}
      - name: Generate graphs
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Graphs CI
          token: ${{ secrets.GH_PAT || github.token }}
      - name: Generate site
        uses: upptime/uptime-monitor@v1.40.1
        with:
          command: "site"
        env:
          GH_PAT: ${{ secrets.GH_PAT || github.token }}
      - uses: peaceiris/actions-gh-pages@v4
        name: GitHub Pages Deploy
        with:
          github_token: ${{ secrets.GH_PAT || github.token }}
          publish_dir: "site/status-page/__sapper__/export/"
          force_orphan: "false"
          user_name: "Upptime Bot"
          user_email: "73812536+upptime-bot@users.noreply.github.com"
